### ISSUE TITLE
Migrate to embedAndSignAppleFrameworkForXcode task

### ISSUE THREAD

**Issue by dcampogiani** [dcampogiani/ktmp#81]
More info here: https://blog.jetbrains.com/kotlin/2021/07/multiplatform-gradle-plugin-improved-for-connecting-kmm-modules/

**Comment by Gioevi90** [comment]
here the pr: https://github.com/dcampogiani/ktmp/pull/82

**Comment by Gioevi90** [comment]
the pr has been merged. We can close this issue
